version: '3.3'
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db-app'
      MYSQL_USER: 'db-admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db-app:/var/lib/mysql
volumes:
  db-app: